### ISSUE TITLE
Add organization_name to user view

### ISSUE THREAD

**Issue by cspital** [uwrit/kpmp_user_portal#34]
`UserView.get_list` is where this is implemented.

1. get super.
2. get orgs from mongo.
3. match and add field.
4. ensure that field does NOT come back during edit.
5. tweak list and detail UI to show the correct fields and deal with them.
6. org name should sortable in list view.

**Comment by jmcarson** [comment]
Implemented using a column formatter which works as well. Will go back and update to use get_list similar to how groups is added as that makes more sense before pull request.

**Comment by jmcarson** [comment]
Update to display org.name by populating in get_list #41 - also added sorting by org name and a search box. Searching by org name when its an added listview field like this does not work. Will try to add a org name filter or add support for searching by org name at some point.
